[2024-12-02T19:01:42.526469+01:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-12-02T19:01:42.526831+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:01:42.526838+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:01:42.526844+01:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:01:42.608566+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-12-02T19:01:42.758185+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:14:34.587092+01:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2024-12-02T19:14:34.587455+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:14:34.587463+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:14:34.587468+01:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:14:34.628077+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-12-02T19:14:34.634654+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:44:17.954904+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T19:44:17.957601+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:44:17.957611+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:44:17.995437+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-12-02T19:44:18.003981+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:45:41.421605+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T19:45:41.422039+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:45:41.422048+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:45:41.459572+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-12-02T19:45:41.467692+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:47:05.117183+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T19:47:05.117617+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:47:05.117624+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:47:05.164543+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"arcadia_test","serverVersion":"8.0.32","charset":"utf8mb4"}} []
[2024-12-02T19:47:05.172062+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:57:52.946608+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T19:57:52.949114+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:57:52.949121+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:57:52.965126+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T19:57:53.039606+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T19:57:53.042541+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T19:57:53.078550+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T19:57:53.082159+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:58:26.896241+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T19:58:26.896656+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:58:26.896663+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:58:26.914061+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T19:58:26.950019+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T19:58:26.964753+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T19:58:26.984220+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T19:58:27.011517+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:58:47.570231+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T19:58:47.570645+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T19:58:47.570652+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T19:58:47.587374+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T19:58:47.607460+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T19:58:47.624697+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T19:58:47.643591+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T19:58:47.657034+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T19:59:48.777896+01:00] console.CRITICAL: Error thrown while running command ""doctrine:fixtures:load" --env=test". Message: "There are no commands defined in the "doctrine:fixtures" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema  You may be looking for a command provided by the "DoctrineFixturesBundle" which is currently not installed. Try running "composer require doctrine/doctrine-fixtures-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\". at C:\\xampp\\htdocs\\Arcadia\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:70)","command":"\"doctrine:fixtures:load\" --env=test","message":"There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\"."} []
[2024-12-02T20:00:56.699196+01:00] console.CRITICAL: Error thrown while running command ""doctrine:fixtures:load" --env=test". Message: "There are no commands defined in the "doctrine:fixtures" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema  You may be looking for a command provided by the "DoctrineFixturesBundle" which is currently not installed. Try running "composer require doctrine/doctrine-fixtures-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\". at C:\\xampp\\htdocs\\Arcadia\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:70)","command":"\"doctrine:fixtures:load\" --env=test","message":"There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\"."} []
[2024-12-02T20:01:01.739516+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:01:01.739940+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:01:01.739947+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:01:01.756870+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:01:01.776819+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:01:01.800198+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:01:01.820071+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:01:01.846090+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T20:02:12.751069+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:02:12.751507+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:02:12.751514+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:02:12.768794+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:02:12.789325+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:02:12.803911+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:02:12.823113+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:02:12.826725+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T20:17:19.579543+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:17:19.579981+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:17:19.579992+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:17:19.597533+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:17:19.618920+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:17:19.633364+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:17:19.652862+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:17:19.680403+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T20:25:48.073528+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:25:48.073957+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:25:48.073969+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:25:48.091298+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:25:48.111655+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:25:48.129070+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:25:48.148709+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:25:48.152253+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T20:32:30.295815+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:32:30.301498+01:00] deprecation.INFO: User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\deprecations\\lib\\Doctrine\\Deprecations\\Deprecation.php:210)"} []
[2024-12-02T20:32:30.301519+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:32:30.323416+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:32:30.330566+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:32:30.353672+01:00] console.CRITICAL: Error thrown while running command "doctrine:schema:update --force --env=test". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)","command":"doctrine:schema:update --force --env=test","message":"An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'"} []
[2024-12-02T20:32:30.356336+01:00] console.DEBUG: Command "doctrine:schema:update --force --env=test" exited with code "1049" {"command":"doctrine:schema:update --force --env=test","code":1049} []
[2024-12-02T20:33:28.497550+01:00] console.CRITICAL: Error thrown while running command ""doctrine:fixtures:load" --env=test". Message: "There are no commands defined in the "doctrine:fixtures" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema  You may be looking for a command provided by the "DoctrineFixturesBundle" which is currently not installed. Try running "composer require doctrine/doctrine-fixtures-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\". at C:\\xampp\\htdocs\\Arcadia\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:70)","command":"\"doctrine:fixtures:load\" --env=test","message":"There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\"."} []
[2024-12-02T20:36:11.620742+01:00] console.CRITICAL: Error thrown while running command ""doctrine:fixtures:load" --env=test". Message: "There are no commands defined in the "doctrine:fixtures" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema  You may be looking for a command provided by the "DoctrineFixturesBundle" which is currently not installed. Try running "composer require doctrine/doctrine-fixtures-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\". at C:\\xampp\\htdocs\\Arcadia\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:70)","command":"\"doctrine:fixtures:load\" --env=test","message":"There are no commands defined in the \"doctrine:fixtures\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema\n\nYou may be looking for a command provided by the \"DoctrineFixturesBundle\" which is currently not installed. Try running \"composer require doctrine/doctrine-fixtures-bundle --dev\"."} []
[2024-12-02T20:38:19.384748+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:38:19.390150+01:00] deprecation.INFO: User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\deprecations\\lib\\Doctrine\\Deprecations\\Deprecation.php:210)"} []
[2024-12-02T20:38:19.390170+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:38:19.392905+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:38:19.393995+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:38:19.395886+01:00] console.CRITICAL: Error thrown while running command "doctrine:fixtures:load --env=test". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)","command":"doctrine:fixtures:load --env=test","message":"An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'"} []
[2024-12-02T20:38:19.398606+01:00] console.DEBUG: Command "doctrine:fixtures:load --env=test" exited with code "1049" {"command":"doctrine:fixtures:load --env=test","code":1049} []
[2024-12-02T20:46:41.511523+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:46:41.514025+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:46:41.514036+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:46:41.532035+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:46:41.557183+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:46:41.582258+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:46:41.602314+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:46:41.628934+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T20:51:05.050201+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:51:05.050674+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:51:05.050683+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:51:05.068615+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:51:05.088730+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:51:05.106106+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:51:05.124852+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:51:05.152807+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T20:52:18.789508+01:00] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://localhost/login_check","method":"POST"} []
[2024-12-02T20:52:18.789930+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2024-12-02T20:52:18.789937+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2024-12-02T20:52:18.806736+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:52:18.827069+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T20:52:18.841318+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T20:52:18.860165+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T20:52:18.889135+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" at ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-12-02T21:03:27.095977+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T21:03:27.102191+01:00] deprecation.INFO: User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\deprecations\\lib\\Doctrine\\Deprecations\\Deprecation.php:210)"} []
[2024-12-02T21:03:27.102214+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T21:03:27.126891+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T21:03:27.139196+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T21:03:27.156512+01:00] console.CRITICAL: Error thrown while running command "doctrine:schema:update --force --env=test". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)","command":"doctrine:schema:update --force --env=test","message":"An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'"} []
[2024-12-02T21:03:27.160426+01:00] console.DEBUG: Command "doctrine:schema:update --force --env=test" exited with code "1049" {"command":"doctrine:schema:update --force --env=test","code":1049} []
[2024-12-02T21:07:08.224933+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T21:07:08.231096+01:00] deprecation.INFO: User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\deprecations\\lib\\Doctrine\\Deprecations\\Deprecation.php:210)"} []
[2024-12-02T21:07:08.231120+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-12-02T21:07:08.245864+01:00] doctrine.INFO: Disconnecting [] []
[2024-12-02T21:07:08.253084+01:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"arcadia_test_test","charset":"utf8mb4"}} []
[2024-12-02T21:07:08.278206+01:00] console.CRITICAL: Error thrown while running command "doctrine:schema:update --force --env=test". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test' at C:\\xampp\\htdocs\\Arcadia\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)","command":"doctrine:schema:update --force --env=test","message":"An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'arcadia_test_test'"} []
[2024-12-02T21:07:08.281065+01:00] console.DEBUG: Command "doctrine:schema:update --force --env=test" exited with code "1049" {"command":"doctrine:schema:update --force --env=test","code":1049} []
